import { Language } from './types';

export const LOCALIZATION_STRINGS = {
  [Language.AR]: {
    appName: "AI فوتو ماجيك",
    uploadImage: "اختر صورة",
    captureImage: "التقط بالكاميرا",
    or: "أو",
    magicTools: "الأدوات السحرية",
    enhance: "تحسين الصورة",
    anime: "تحويل لأنمي",
    edit: "تعديل الملامح",
    background: "إزالة الخلفية",
    enhanceDesc: "تحسين الجودة وإزالة التشويش",
    animeDesc: "حوّل صورتك لعدة أنماط كرتونية",
    editDesc: "غيّر ملامح الوجه بنص",
    backgroundDesc: "إزالة الخلفية بضغطة زر",
    generate: "نفّذ",
    download: "تحميل الصورة",
    processing: "جاري المعالجة...",
    error: "حدث خطأ. الرجاء المحاولة مرة أخرى.",
    bannerAd: "مساحة إعلانية",
    editPromptPlaceholder: "مثال: أضف ابتسامة، غير لون الشعر إلى أزرق",
    animeStyle: "اختر نمط",
    japaneseAnime: "أنمي ياباني",
    disneyPixar: "ديزني/بيكسار",
    cartoon3d: "كرتون ثلاثي الأبعاد",
    selectTool: "اختر أداة للبدء",
    uploadFirst: "الرجاء رفع صورة أولاً",
    cameraError: "لا يمكن الوصول إلى الكاميرا.",
    before: "قبل",
    after: "بعد",
    cancel: "إلغاء",
    login: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    logout: "تسجيل الخروج",
    subscribe: "اشترك",
    welcome: "أهلاً",
    name: "الاسم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    createAccount: "أنشئ حسابك",
    loginToAccount: "سجل الدخول لحسابك",
    haveAccount: "لديك حساب بالفعل؟",
    needAccount: "ليس لديك حساب؟",
    loginFailed: "فشل تسجيل الدخول. تحقق من بريدك الإلكتروني وكلمة المرور.",
    registrationFailed: "فشل التسجيل. حاول مرة أخرى.",
    userExists: "هذا المستخدم موجود بالفعل. الرجاء تسجيل الدخول.",
    subscribeNow: "اشترك الآن للوصول الكامل",
    subscriptionRequired: "الاشتراك مطلوب",
    subscribeToUnlock: "لفتح جميع الأدوات السحرية، يرجى الاشتراك.",
    subscribeFor3USD: "اشترك الآن (3 دولار شهرياً)",
    renewSubscription: "تجديد الاشتراك",
    loginToUseTools: "الرجاء تسجيل الدخول لاستخدام أدوات التعديل.",
    subscriptionExpired: "انتهت صلاحية اشتراكك. يرجى التجديد للمتابعة.",
    landingTitle: "أطلق العنان لإبداعك",
    landingSubtitle: "حوّل صورك العادية إلى أعمال فنية مذهلة باستخدام قوة الذكاء الاصطناعي.",
    getStarted: "ابدأ الآن",
    signUpAndPay: "أنشئ حساباً وادفع",
    renewAndLogin: "جدد الاشتراك وسجل الدخول",
    forgotPassword: "نسيت كلمة المرور؟",
    resetPassword: "إعادة تعيين كلمة المرور",
    sendResetCode: "أرسل رمز إعادة التعيين",
    checkYourEmailForCode: "تحقق من بريدك الإلكتروني",
    resetCodeSent: "تم إرسال رمز إعادة التعيين المكون من 6 أرقام إلى بريدك الإلكتروني.",
    enterCode: "أدخل الرمز",
    newPassword: "كلمة المرور الجديدة",
    changePassword: "تغيير كلمة المرور",
    invalidCode: "رمز غير صالح أو منتهي الصلاحية.",
    passwordResetSuccess: "تمت إعادة تعيين كلمة المرور بنجاح. الرجاء تسجيل الدخول.",
    userNotFound: "لم يتم العثور على مستخدم بهذا البريد الإلكتروني.",
    backToLogin: "العودة لتسجيل الدخول",
  },
  [Language.EN]: {
    appName: "AI Photo Magic",
    uploadImage: "Select Photo",
    captureImage: "Capture with Camera",
    or: "OR",
    magicTools: "Magic Tools",
    enhance: "Enhance Image",
    anime: "Anime Conversion",
    edit: "Feature Edit",
    background: "Remove Background",
    enhanceDesc: "Improve quality and remove noise",
    animeDesc: "Convert your photo to various cartoon styles",
    editDesc: "Change facial features with text",
    backgroundDesc: "Remove the background with one click",
    generate: "Generate",
    download: "Download Image",
    processing: "Processing...",
    error: "An error occurred. Please try again.",
    bannerAd: "Banner Ad Space",
    editPromptPlaceholder: "e.g., add a smile, change hair color to blue",
    animeStyle: "Choose Style",
    japaneseAnime: "Japanese Anime",
    disneyPixar: "Disney/Pixar",
    cartoon3d: "3D Cartoon",
    selectTool: "Select a tool to start",
    uploadFirst: "Please upload an image first",
    cameraError: "Could not access the camera.",
    before: "Before",
    after: "After",
    cancel: "Cancel",
    login: "Login",
    signUp: "Sign Up",
    logout: "Logout",
    subscribe: "Subscribe",
    welcome: "Welcome",
    name: "Name",
    email: "Email",
    password: "Password",
    createAccount: "Create your account",
    loginToAccount: "Login to your account",
    haveAccount: "Already have an account?",
    needAccount: "Don't have an account?",
    loginFailed: "Login failed. Check your email and password.",
    registrationFailed: "Registration failed. Please try again.",
    userExists: "User already exists. Please log in.",
    subscribeNow: "Subscribe now for full access",
    subscriptionRequired: "Subscription Required",
    subscribeToUnlock: "To unlock all magic tools, please subscribe.",
    subscribeFor3USD: "Subscribe Now ($3/month)",
    renewSubscription: "Renew Subscription",
    loginToUseTools: "Please log in to use the editing tools.",
    subscriptionExpired: "Your subscription has expired. Please renew to continue.",
    landingTitle: "Unleash Your Creativity",
    landingSubtitle: "Transform your ordinary photos into stunning works of art with the power of AI.",
    getStarted: "Get Started",
    signUpAndPay: "Sign Up & Pay",
    renewAndLogin: "Renew & Login",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    sendResetCode: "Send Reset Code",
    checkYourEmailForCode: "Check Your Email",
    resetCodeSent: "A 6-digit reset code has been sent to your email.",
    enterCode: "Enter Code",
    newPassword: "New Password",
    changePassword: "Change Password",
    invalidCode: "Invalid or expired code.",
    passwordResetSuccess: "Password has been reset successfully. Please log in.",
    userNotFound: "User with this email not found.",
    backToLogin: "Back to Login",
  }
};